version: '3'
services:
  db:
   image: mysql:5.7
   volumes:
      - db_data:/var/lib/mysql
   restart: always
   environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
   depends_on:
      - db
   image: wordpress:5.6.2-php8.0-apache
   ports:
      - 8000:80
   restart: always
   environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 1
   volumes: 
      - wp_data:/var/www/html

  wordpress-cli:
   depends_on:
      - db
      - wordpress
   image: wordpress:cli
   user: xfs
   command: >
      /bin/sh -c '
      sleep 10;
      wp core install --path="/var/www/html" --url="http://localhost:8000" --title="MaPage" --admin_user=admin --admin_password=secret --admin_email=perso@hotmail.com
      '
   volumes:
      - wp_data:/var/www/html

  phpmyadmin:
   depends_on:
      - db
   image: phpmyadmin
   ports:
      - 8080:80
   restart: always
   volumes:
      - db_data:/var/lib/mysql
   environment:
      PMA_PASSWORD: wordpress
      PMA_USER: wordpress
      PMA_ARBITRARY: 1

volumes:
  db_data: {}
  wp_data: {}
